robot_cfg:
    kinematics:
        use_usd_kinematics: False
        usd_path: "robot/betabot2/robot_calibrated_root.usd"
        usd_robot_root: "/onshape"
        usd_flip_joints: {}
        usd_flip_joint_limits: []

        urdf_path: "robot/betabot2/robot_calibrated_root.urdf"
        asset_root_path: "robot/betabot2"

        base_link: "root_link"
        ee_link: "urdf_gripper_body"

        collision_link_names: [
          "base_link",
          "urdf_boom_base",
          "urdf_boom_mid",
          "urdf_boom_top",
          "urdf_shoulder_low",
          "urdf_shoulder_high",
          "urdf_forearm_base",
          "urdf_forearm_mid",
          "urdf_forearm_top",
          "urdf_wrist_pitch",
          "urdf_gripper_body",
          "gear_arm_l",
          "gear_arm_r",
          "urdf_jaw_r",
          # "simbot_week_3_wheel_2",
          # "simbot_week_3_wheel",
          "attached_object",
        ]
        
        collision_spheres: "spheres/betabot_mesh.yml"
        collision_sphere_buffer: 0.005
      
        extra_collision_spheres: {"attached_object": 4}
        use_global_cumul: True
        self_collision_ignore: {
          "base_link": ["urdf_boom_base", "urdf_boom_mid", "urdf_boom_top", "urdf_shoulder_low", "urdf_shoulder_high", "urdf_forearm_base", "urdf_forearm_mid", "urdf_forearm_top", "urdf_wrist_pitch", "urdf_gripper_body", "gear_arm_l", "gear_arm_r", "urdf_jaw_r"],
          "urdf_boom_base": ["urdf_boom_mid", "urdf_boom_top", "urdf_shoulder_low", "urdf_shoulder_high", "urdf_forearm_base", "urdf_forearm_mid", "urdf_forearm_top", "urdf_wrist_pitch", "urdf_gripper_body", "gear_arm_l", "gear_arm_r", "urdf_jaw_r"],
          "urdf_boom_mid": ["urdf_boom_top", "urdf_shoulder_low", "urdf_shoulder_high", "urdf_forearm_base", "urdf_forearm_mid", "urdf_forearm_top", "urdf_wrist_pitch", "urdf_gripper_body", "gear_arm_l", "gear_arm_r", "urdf_jaw_r"],
          "urdf_boom_top": ["urdf_shoulder_low", "urdf_shoulder_high", "urdf_forearm_base", "urdf_forearm_mid", "urdf_forearm_top", "urdf_wrist_pitch", "urdf_gripper_body", "gear_arm_l", "gear_arm_r", "urdf_jaw_r"],
          "urdf_shoulder_low": ["urdf_shoulder_high", "urdf_forearm_base", "urdf_forearm_mid", "urdf_forearm_top", "urdf_wrist_pitch", "urdf_gripper_body", "gear_arm_l", "gear_arm_r", "urdf_jaw_r"],
          "urdf_shoulder_high": ["urdf_forearm_base", "urdf_forearm_mid", "urdf_forearm_top", "urdf_wrist_pitch", "urdf_gripper_body", "gear_arm_l", "gear_arm_r", "urdf_jaw_r"],
          "urdf_forearm_base": ["urdf_forearm_mid", "urdf_forearm_top", "urdf_wrist_pitch", "urdf_gripper_body", "gear_arm_l", "gear_arm_r", "urdf_jaw_r"],
          "urdf_forearm_mid": ["urdf_forearm_top", "urdf_wrist_pitch", "urdf_gripper_body", "gear_arm_l", "gear_arm_r", "urdf_jaw_r"],
          "urdf_forearm_top": ["urdf_wrist_pitch", "urdf_gripper_body", "gear_arm_l", "gear_arm_r", "urdf_jaw_r"],
          "urdf_wrist_pitch": ["urdf_gripper_body", "gear_arm_l", "gear_arm_r", "urdf_jaw_r"],
          "urdf_gripper_body": ["gear_arm_l", "gear_arm_r", "urdf_jaw_r", "attached_object"],
          "gear_arm_l": ["gear_arm_r", "urdf_jaw_r", "attached_object"],
          "gear_arm_r": ["urdf_jaw_r", "attached_object"],
          "urdf_jaw_r": ["attached_object", "attached_object"],
          } 

        self_collision_buffer: {
          "base_link": 0.01,
          "urdf_boom_base": 0.0,
          "urdf_boom_mid": 0.0,
          "urdf_boom_top": 0.0,
          "urdf_shoulder_low": 0.0,
          "urdf_shoulder_high": 0.0,
          "urdf_forearm_base": 0.0,
          "urdf_forearm_mid": 0.0,
          "urdf_forearm_top": 0.0,
          "urdf_wrist_pitch": 0.0,
          "urdf_gripper_body": 0.01,
          "gear_arm_l": 0.01,
          "gear_arm_r": 0.01,
          "urdf_jaw_r": 0.01,
          "attached_object": 0.0,
          # "simbot_week_3_wheel_2": 0.0,
          # "simbot_week_3_wheel": 0.0,
          }

        mesh_link_names:
          [
          "base_link",
          "urdf_boom_base",
          "urdf_boom_mid",
          "urdf_boom_top",
          "urdf_shoulder_low",
          "urdf_shoulder_high",
          "urdf_forearm_base",
          "urdf_forearm_mid",
          "urdf_forearm_top",
          "urdf_wrist_pitch",
          "urdf_gripper_body",
          "gear_arm_l",
          "gear_arm_r",
          "urdf_jaw_r",
          # "simbot_week_3_wheel_2",
          # "simbot_week_3_wheel",
          ]

        # lock_joints: {"boom_mid_extension_passive": 0.02, "boom_top_extension": 0.04, "forearm_mid_extension_passive": 0.02, "forearm_top_extension": 0.04}
        extra_links: {"attached_object":{"parent_link_name": "urdf_gripper_body" ,
          "link_name": "attached_object", "fixed_transform": [0,0,0,1,0,0,0], "joint_type":"FIXED",
          "joint_name": "attach_joint" }}

        cspace: 
          joint_names: [
            "root_link_linear_x_joint",
            "root_link_linear_y_joint",
            "root_link_angular_joint",
            "boom_tilt",
            "boom_mid_extension_passive",
            "boom_top_extension",
            "shoulder_rotate",
            "shoulder_tilt",
            "forearm_mid_extension_passive",
            "forearm_top_extension",
            "forearm_roll",
            "wrist_pitch_revolute",
            "wrist_yaw",]
            # "left_wheel",
            # "right_wheel"]
            
          retract_config:   [0.0, 0.0, 0.0, 0.15, 0.1, 0.1, 0.0, -0.3, 0, 0.05, 0.05, -0.4, 0.0]
          null_space_weight:  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
          cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
          max_acceleration: 15.0
          max_jerk: 500.0

        