robot_cfg:
    kinematics:
        use_usd_kinematics: False
        usd_path: "robot/gammabot/robot_root.usd"
        usd_robot_root: "/onshape"
        usd_flip_joints: {}
        usd_flip_joint_limits: []

        urdf_path: "robot/gammabot/robot_root.urdf"
        asset_root_path: "robot/gammabot"

        base_link: "root_link"
        ee_link: "gripper"

        collision_link_names: [
          "base_link",
          "boom_base",
          "boom_extension",
          "composite_part_6",
          "composite_part_7",
          "forearm_extension",
          "wrist_roll",
          "wrist_pitch",
          "gripper",
          "attached_object",
        ]
        collision_spheres: "spheres/gammabot_mesh.yml"
        collision_sphere_buffer: 0.002 #0.02
        extra_collision_spheres: {"attached_object": 4}
        use_global_cumul: True
        self_collision_ignore: {
          "base_link": ["boom_base", "boom_extension","composite_part_6", "composite_part_7", "forearm_extension", "wrist_roll", "wrist_pitch", "gripper"],
          "boom_base": ["boom_extension","composite_part_6", "composite_part_7", "forearm_extension", "wrist_roll", "wrist_pitch", "gripper"],
          "boom_extension": ["composite_part_6", "composite_part_7", "forearm_extension", "wrist_roll", "wrist_pitch", "gripper"],
          "composite_part_6": ["composite_part_7", "forearm_extension", "wrist_roll", "wrist_pitch", "gripper"],
          "composite_part_7": ["forearm_extension", "wrist_roll", "wrist_pitch", "gripper"],
          "forearm_extension": ["wrist_roll", "wrist_pitch", "gripper"],
          "wrist_roll": ["wrist_pitch", "gripper"],
          "wrist_pitch": ["gripper"],
          "gripper": ["attached_object"],
          } 

        self_collision_buffer: {
          "base_link": 0.01,
          "boom_base": 0.00,
          "boom_extension": 0.00,
          "composite_part_6": 0.00,
          "composite_part_7": 0.00,
          "forearm_extension": 0.00,
          "wrist_roll": 0.00,
          "wrist_pitch": 0.00,
          "gripper": 0.02,
          "attached_object": 0.00,
          }

        mesh_link_names:
          [
          "base_link",
          "boom_base",
          "boom_extension",
          "composite_part_6",
          "composite_part_7",
          "forearm_extension",
          "wrist_roll",
          "wrist_pitch",
          "gripper",
          ]

        # lock_joints: {"boom_mid_extension_passive": 0.02, "boom_top_extension": 0.04, "forearm_mid_extension_passive": 0.02, "forearm_top_extension": 0.04}
        extra_links: {"attached_object":{"parent_link_name": "gripper" ,
          "link_name": "attached_object", "fixed_transform": [0,0,0,1,0,0,0], "joint_type":"FIXED",
          "joint_name": "attach_joint" }}

        cspace: 
          joint_names: [
            "root_link_linear_x_joint",
            "root_link_linear_y_joint",
            "root_link_angular_joint",
            "boom_tilt_joint",
            "boom_extension_joint",
            "boom_swivel_joint",
            "shoulder_tilt_joint",
            "forearm_extension_joint",
            "forearm_roll_joint",
            "wrist_pitch_joint",
            "wrist_roll_joint",]

          retract_config:   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.81, 0.0, 0.0, -0.5, -1.57]
          null_space_weight:  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
          cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,  1.0, 1.0, 1.0, 1.0]
          max_acceleration: 15.0
          max_jerk: 500.0